### ISSUE TITLE
How to access the login

### ISSUE THREAD

**Issue by LZS1991** [PanagiotisDrakatos/SpringBoot-Registration-Login-ThePerfectExample#1]
I test your program，but i find that i can not visit the login page by using "127.0.0.1:8443/login.html"
so how can i visit the website?

**Comment by PanagiotisDrakatos** [comment]
if you have an Exception please Follow the Readme you probably not setup the mysql properly. If the problem still exists feel free to post the exception here. If no exception was thrown but the page was not open try open https link "https://127.0.0.1:8443/" and not 127.0.0.1:8443/login.html"

**Comment by LZS1991** [comment]
I can run it use the https now,but there still some exception
when i register ,there wll be an exception:
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching www.google.com found.

**Comment by PanagiotisDrakatos** [comment]
Please be more specific. If i understand properly you are able to open the registration page with success but when you clicked the registration button you got the exception
