### ISSUE TITLE
Cannot run App.java

### ISSUE THREAD

**Issue by my-moctopus** [PanagiotisDrakatos/SpringBoot-Registration-Login-ThePerfectExample#4]
Why I open the code and it doesn't find App.java as Spring boot (main) application to run?

Regards,
Dan

**Comment by PanagiotisDrakatos** [comment]
@my-moctopus <p>Your answer is too unclear. If I understand correctly you don't set up which class will be loaded as main.class from your IDE. Assume that you use IntelliJ check all the answers(the answer lays there) of this <a href="https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000156824-How-to-choose-main-class">post<a/> of how to set up properly a main.class for any project.</p>

**Comment by my-moctopus** [comment]
Sorry, I'm new for Java and gave the unclear information to you.
1. Choose Spring boot class:
![image](https://user-images.githubusercontent.com/46044547/52318127-91b81f00-29f5-11e9-99a6-d10f49b1c80e.png)

2. Normally, After I checked out the source code from git. It can be right click and execute the main class as spring boot.

Regards,
Dan

**Comment by my-moctopus** [comment]
Hi @PanagiotisDrakatos ,

I've fixed it by add maven xml by use the dependency-reduce-pom.xml instead of pom.xml

Regards,
Dan
